### ISSUE TITLE
Use of ETIP trackers signatures instead of εxodus's ones

### ISSUE THREAD

**Issue by codeurimpulsif** [thebozzcl/ExodusPiHole#1]
The `generate.sh` script use an ETIP endpoint to get trackers network signatures, but the ETIP database contains also trackers that are not validated so it can contain false positives or other bad patterns.

Maybe a better idea is to use the [`/api/trackers` εxodus API endpoint](https://github.com/Exodus-Privacy/exodus/blob/v1/doc/api.md#get-the-list-of-trackers) which return only validated trackers present in the εxodus production database (and also contain network signatures of course).

**Comment by thebozzcl** [comment]
Seems fair, but I do want to keep the ETIP endpoint as an option. I'll refactor the code so it compiles both lists, then I'll change `update-exodus.sh` so we can specify the file but defaulting to the safer endpoint.

**Comment by thebozzcl** [comment]
Hmmm. They mention they need an API key, but they don't seem to enforce it actively in either ETIP or the regular list. I'm gonna request an API key and add that as an option, seems like the right thing to do.

**Comment by thebozzcl** [comment]
Alright, all code updated and working. AuthZ is still not in place since I'm blocked by Exodus, but I'll update the code to add that once they reply. The README's been updated too to reflect this (and other details I forgot to document before).

Thanks for your feedback!
