### ISSUE TITLE
Pi-hole fails to read long regexes

### ISSUE THREAD

**Issue by thebozzcl** [thebozzcl/ExodusPiHole#2]
For example:
```
  [✗] grid\.amap\.com|tm\.amap\.com|mst[0-9]*\.is\.autonavi\.com|mt[0-9]*\.google\.cn|abroad\.apilocate\.amap\.com|apilocate\.amap\.com|restapi\.amap\.com|yuntuapi\.amap\.com|m5\.amap\.com|wb\.amap\.com|wb\.amap\.com|wb\.amap\.com|wb\.amap\.com|apiinit\.amap\.com|restapi\.amap\.com|logs\.amap\.com|cgicol\.amap\.com|lbs\.amap\.com|wap\.amap\.com is not a valid argument or domain name!
```
These can be added manually through the web GUI, but I wonder if there's an automated option.

**Comment by scottwallacesh** [comment]
As the pipes simply mean logical OR, why not simply replace them with a newline?

e.g. `... | sed s/'|'/'\n'/g | sort -u`

The example line then becomes,

```text
abroad\.apilocate\.amap\.com
apiinit\.amap\.com
apilocate\.amap\.com
cgicol\.amap\.com
grid\.amap\.com
lbs\.amap\.com
logs\.amap\.com
m5\.amap\.com
mst[0-9]*\.is\.autonavi\.com
mt[0-9]*\.google\.cn
restapi\.amap\.com
tm\.amap\.com
wap\.amap\.com
wb\.amap\.com
yuntuapi\.amap\.com
```

**Comment by thebozzcl** [comment]
I thought about doing something similar, but I discarded it because it assumes the Exodus patterns will never include pipes as part of inner blocks of the regex. Something like this, for example:
```javascript
(subdomain1|subdomain2)\.example\.com
```

In practice, I don't remember seeing anything similar within the current results, so your approach would work... but there's no guarantee it will remain compatible in the future. If you tested your PR and it's working for the moment I'd be okay merging it in until I come up with a future-proof solution.

**Comment by thebozzcl** [comment]
I tested your PR and at least for now everything works OK. I'll keep an eye for the next updates, though I should probably just use a linter of sorts to confirm all the regexes are fine.
